Assignment/Models/Data.cs
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.Xml.Linq;

namespace Assignment.Models
{
    public class Data
    {
        public int Id { get; set; }
     
        public string Full_Name { get; set; }

        public string Email { get; set; }

        public string Phone { get; set; }

    }
    public class info
    {
        public int P_id { get; set; }

        public string P_Name { get; set; }

        public float price { get; set; }


    }
}

Assignment/Models/ErrorViewModel.cs
namespace Assignment.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Assignment/Models/Userlogin.cs
namespace Assignment.Models
{
    public class Userlogin
    { 
        public string Username { get; set; }
        public String Password { get; set; }
    }
}

Assignment/Models/viewModel/LoginsignupviewModel.cs
namespace Assignment.Models.viewModel
{
    public class LoginsignupviewModel
    {
        public int Id { get; set; }



        public string User_Name { get; set; }

        public string Email { get; set; }

        public string Password { get; set; }

        public string ConfirmPassword { get; set; }

        public string phone { get; set; }
        public bool isActive { get; set; }


        public bool IsRemember { get; set; }



    }
}

Assignment/Controllers/Account/AccountController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using System.Security.Claims;
using Assignment.Models;

namespace Assignment.Controllers.Account

{
    public class AccountController : Controller
    {

       
            public IActionResult login()
            {
                ViewData["error"] = "";
                return View();
            }

            [HttpPost]
            public IActionResult Login(Userlogin model)
            {
                //check from db
                string connString = "server=ENGKALIT; database=Bookshop;integrated security=true; TrustServerCertificate=True;";
                using (SqlConnection con = new SqlConnection(connString))
                {
                    con.Open();
                    string query = $"select count(*) total from login where UserName='{model.Username}' and Password='{model.Password}'";
                    SqlCommand cmd = new SqlCommand(query, con);
                    int count = Convert.ToInt32(cmd.ExecuteScalar());
                    if (count > 0)
                    {
                        //user is valid
                        //create session
                        HttpContext.Session.SetString("UserName", model.Username);

                        //give auth cookie
                        var claims = new List<Claim>()
                    {
                        new Claim(ClaimTypes.NameIdentifier, model.Username),
                        new Claim(ClaimTypes.Role,"Admin")

                    };

                        var identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                        var princible = new ClaimsPrincipal(identity);
                        HttpContext.SignInAsync(princible);




                        return RedirectToAction("Index", "Home");
                    }
                    else
                    {
                        //user is invalid
                        ViewData["error"] = "Invalid Credentials";
                        return View(model);
                    }


                }

            }

            public IActionResult logout()
            {
                HttpContext.Session.Remove("username");
                HttpContext.SignOutAsync();
                return RedirectToAction("login");
            }
        }

    }

Assignment/Controllers/Account/CustomerRepController.cs
using Assignment.Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Assignment.Models;
using Microsoft.AspNetCore.Authorization;

namespace Assignment.Controllers.Account
{
    [Authorize]

    public class CustomerRepController : Controller
    {
        CustomerDetails cust;

        public CustomerRepController()
        {
            cust = new CustomerDetails();
        }
        public IActionResult Signin()

        {
            try
            {
                if (HttpContext.Session.GetString("UserName") == null)
                {
                    return RedirectToAction("login", "Account");

                }
                return View();
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = "An error occurred: " + ex.Message;
                return View();

            }
        }

        public IActionResult inddex()
        {
            try
            {
                var data = cust.getAll();
                return View(data);
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = "An error occurred: " + ex.Message;
                return View();

            }
        }

        public IActionResult Register()
        {
            try
            {
                return View();
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = "An error occurred: " + ex.Message;
                return View();

            }
        }
            [HttpPost]
        public IActionResult Register(Data model)
        {


            cust.Register(model.Full_Name,model.Email,model.Phone);
            return RedirectToAction("inddex");
        }
        public IActionResult update() {

            return View(); 
        }
        [HttpPost]
        //public IActionResult update(Data model)
        //{
        //    cust.update(model.Full_Name, model.Email, model.Phone);
        //    return RedirectToAction("index");
        //}
        public IActionResult update(Data model)
        {
            cust.update(model.Id,model.Full_Name, model.Email, model.Phone);
            return RedirectToAction("inddex");
        }
        public IActionResult Dlete()
        {  return View();
        }
        [HttpPost]
        public IActionResult Delete(Data model)
        {

            cust.delete(model.Id);
            return RedirectToAction("Index");
        }

    }
}

  
        

Assignment/Controllers/Account/ProductController.cs
using Assignment.Models;
using Assignment.Repository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Templates.BlazorIdentity.Pages.Manage;
using System.Xml.Linq;

namespace Assignment.Controllers.Account
{
    [Authorize]
    public class ProductController : Controller
    {
     
        Products repo;
        public ProductController()
        {
            repo = new Products();


        }
        public IActionResult Index()
        {
            var data = repo.getAll();
            return View(data);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(info model)
        {
            repo.create(model. P_Name, model. price );
            return RedirectToAction("index");
        }

        public IActionResult Edit(int id)
        {
            var found = repo.get_by_id(id);
            return View(found);
        }
   
        [HttpPost]
        public IActionResult Edit(info model)
        {
            repo.Edit(model.P_id, model.P_Name, model.price);
            return RedirectToAction("index");
        }

        public IActionResult Delete(int id)
        {
            var found = repo.get_by_id(id);
            return View(found);
        }

        [HttpPost]
        public IActionResult Delete(info model)
        {

            repo.delete(model.P_id);
            return RedirectToAction("Index");
        }

    }
}

Assignment/Controllers/HomeController.cs
using Assignment.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Assignment.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Assignment/Views/CustomerRep/Dlete.cshtml
@model Data;
<h3>Confirm: do you want to delete?</h3>
<br />

<form method="post" asp-action="Dlete">
    <input type="hidden" asp-for="Id" />
    <div class="form-group">
        <label class="form-label"> FullName</label>
        <input asp-for="Full_Name" class="form-control" disabled />
    </div>

    <br /><br />
   

    <br /><br /><div class="form-group">
        <label class="form-label"> email;</label>
        <input asp-for="Email" class="form-control" disabled />
    </div>

    <br /><br />
    <div class="form-group">
        <label class="form-label"> Phone:</label>
        <input asp-for="Phone" class="form-control" disabled />
    </div>

    <br /><br /> <a class="btn btn-primary" asp-action="Index">Cancel</a>
    <button type="submit" class="btn btn-danger">Yes, Delete !</button>

</form>

Assignment/Views/CustomerRep/Inddex.cshtml
@model List<Data>;
<h3>List of Customers</h3>
<br />
<a class="btn btn-primary" asp-action="Register">
    Diwaan Gali macmiil Cusub</a>
<br />
<br />
<table class="table table-bordered">
    <thead>
        <tr>
            <th>#</th>
            <th style="width:80%;">Name</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @{
            int counter = 1;
        }
        @foreach (var item in Model)
        {
            <tr>
                <td>@counter</td>
                <td>@item.Full_Name</td>
               
                <td>@item.Email</td>
                <td>@item.Phone</td>
                <td>
                    <a class="btn btn-success"  asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                    <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
            counter++;

        }
    </tbody>
</table>

Assignment/Views/CustomerRep/Index.cshtml
@model List<info>;
<h3>List of Products</h3>
<br />
<a class="btn btn-primary" asp-action="Create">New Products</a>
<br />
<br />
<table class="table table-bordered">
    <thead>
        <tr>
            <th>#</th>
            <th style="width:50%;">Name</th>
              <th >Price</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @{
            int counter = 1;
        }
        @foreach (var item in Model)
        {
            <tr>
                <td>@counter</td>
                <td>@item.P_Name</td>
                 <td>@item.price</td>
                <td>
                    <a class="btn btn-success" asp-action="Edit" asp-route-id="@item.P_id">Edit</a>
                    <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.P_id">Delete</a>
                </td>
            </tr>
            counter++;

        }
    </tbody>
</table>

Assignment/Views/CustomerRep/Register.cshtml
@model Data;

<h3>Register New Customer </h3>
<br />

<form method="post" asp-action="Register">

    <div class="form-group" width="70%">
        <label class="form-label">FullName:  </label>
        <input asp-for="Full_Name" class="form-control" />

    </div>
    <br /><br />

    <div class="form-group" width="70%">
        <label class="form-label">Email ::  </label>
        <input asp-for="Email" class="form-control" />

    </div>
    <br /><br />

    <div class="form-group" width ="70%">
    <label class="form-label">PHONE:  </label>
    <input asp-for="Phone" class="form-control" />

    </div>
    <br /><br />



   

 

    <a class="btn btn-danger" asp-action="Inddex">Cancel</a>
    <button type="submit" class="btn btn-primary">Save</button>

</form>

Assignment/Views/CustomerRep/update.cshtml
@model Data;

<h3>update Customer</h3>
<br />

<form method="post" asp-action="update">

    <div class="form-group">
        <label class="form-label"> customer Name :</label>
        <input asp-for="Full_Name" class="form-control" />
    </div>
   


    <br /><br />
    <div class="form-group">
        <label class="form-label"> Email :</label>
        <input asp-for="Email" class="form-control" />
    </div>


    <br /><br />
    <div class="form-group">
        <label class="form-label"> PHONE :</label>
        <input asp-for="Phone" class="form-control" />
    </div>


    <br /><br />
    <a class="btn btn-danger" asp-action="Index">Cancel</a>
    <button type="submit" class="btn btn-primary">Save</button>

</form>

Assignment/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Assignment/Views/Product/Create.cshtml
@model info;

<h3>Create New Product</h3>
<br />

<form method="post" asp-action="Create">

    <div class="form-group">
        <label class="form-label"> Product Name</label>
        <input asp-for="P_Name" class="form-control" />
    </div>

    <div class="form-group">
        <label class="form-label"> Product Price</label>
        <input asp-for="price" class="form-control" />
    </div>


    <br /><br />

    <a class="btn btn-danger" asp-action="Index">Cancel</a>
    <button type="submit" class="btn btn-primary">Save</button>

</form>

Assignment/Views/Product/Delete.cshtml
@model info;
<h3>Confirm: do you want to delete?</h3>
<br />

<form method="post" asp-action="Delete">
    <input type="hidden" asp-for="P_id" />
    <div class="form-group">
        <label class="form-label"> product Name</label>
        <input asp-for="P_Name" class="form-control" disabled />
    </div>

    <br /><br />

    <a class="btn btn-primary" asp-action="Index">Cancel</a>
    <button type="submit" class="btn btn-danger">Yes, Delete !</button>

</form>

Assignment/Views/Product/Edit.cshtml
@model info;

<h3>Update New Product</h3>
<br />

<form method="post" asp-action="Edit">

    <div class="form-group">
        <label class="form-label"> Product Name</label>
        <input asp-for="P_Name" class="form-control" />
    </div>

    <div class="form-group">
        <label class="form-label"> Product Price</label>
        <input asp-for="price" class="form-control" />
    </div>


    <br /><br />

    <a class="btn btn-danger" asp-action="Index">Cancel</a>
    <button type="submit" class="btn btn-primary">Save</button>

</form>

Assignment/Views/Product/Index.cshtml
@model List<info>;
<h3>List of Products</h3>
<br />
<a class="btn btn-primary" asp-action="Create">New Products</a>
<br />
<br />
<table class="table table-bordered">
    <thead>
        <tr>
            <th>#</th>
            <th style="width:50%;">Name</th>
            <th>Price</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @{
            int counter = 1;
        }
        @foreach (var item in Model)
        {
            <tr>
                <td>@counter</td>
                <td>@item.P_Name</td>
                <td>@item.price</td>
                <td>
                    <a class="btn btn-success" asp-action="Edit" asp-route-id="@item.P_id">Edit</a>
                    <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.P_id">Delete</a>
                </td>
            </tr>
            counter++;

        }
    </tbody>
</table>

Assignment/Views/Shared/_General.cshtml
<ul class="menu">
    <li>@Html.ActionLink("LIST", "Register", "CustomerRepo")</li>
    <li>@Html.ActionLink("Product", "Index", "Product")</li>
    <li>@Html.ActionLink("About", "About", "Main")</li>
    <li>@Html.ActionLink("Create", "Create", "Main")</li>

    <!-- Add more menu items as needed -->
</ul>

Assignment/Views/Shared/_Layout _Login.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Assignment</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Assignment.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Assignment</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Assignment - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Assignment/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Assignment</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Assignment.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Assignment</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CustomerRep" asp-action="Register">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CustomerRep" asp-action="Edit">Update Products

                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Assignment - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>